#pragma once
#include <iostream>
#include <pcl/visualization/cloud_viewer.h>
#include <pcl/io/io.h>
#include <pcl/io/pcd_io.h>
#pragma comment(lib,"pcl_common_release.lib")
#pragma comment(lib,"pcl_io_release.lib")
#pragma comment(lib,"pcl_visualization_release.lib")
#pragma comment(lib,"vtkCommonCore-6.2.lib")
#pragma comment(lib,"vtkalglib-6.2.lib")
#pragma comment(lib,"vtkCommonExecutionModel-6.2.lib")
#pragma comment(lib,"vtkRenderingLOD-6.2.lib")
#pragma comment(lib,"vtkRenderingOpenGL-6.2.lib")
#pragma comment(lib,"vtkRenderingCore-6.2.lib")
#pragma comment(lib,"vtkFiltersSources-6.2.lib")