#include <thrust\host_vector.h>
#include <thrust\device_vector.h>
#include <thrust\generate.h>
#include <thrust\reduce.h>
#include <thrust\functional.h>
#include <thrust\transform.h>
#include <thrust\sequence.h>
#include <thrust\copy.h>
#include <thrust\fill.h>
#include <thrust\replace.h>